# Generated by Django 2.0.1 on 2019-04-25 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj1', '0003_auto_20190425_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Data',
        ),
    ]
