# Generated by Django 2.0.1 on 2019-04-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj1', '0004_auto_20190425_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proj1.USER_LOGIN'),
        ),
    ]
